nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.1.cjs

npmScopes:
    mrgnlabs:
        npmAlwaysAuth: true
        npmAuthToken: "${CODEARTIFACT_AUTH_TOKEN}"
        npmRegistryServer: "https://aperture-717731509644.d.codeartifact.us-east-1.amazonaws.com/npm/aperture/"
        npmPublishRegistry: "https://aperture-717731509644.d.codeartifact.us-east-1.amazonaws.com/npm/aperture/"